language: node_js
node_js:
  - 'lts/*'
cache:
  directories:
    - node_modules
script:
  - yarn lint
  - yarn test
  - yarn build
  - yarn size

deploy:
  provider: pages:git
  token: $github_token
  local_dir: build
  edge: true # opt in to dpl v2
